name: Publish to nuget
on:
  release: 
    types: [created]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Publish to NuGet
        run: |
          dotnet pack -c Release --include-source --include-symbols --nologo -o ./packed
          dotnet nuget push "./packed/*" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
